create table if not exists user_chat (
    id bigint generated by default as identity primary key not null,
    user_id UUID not null,
    chat_id bigint not null,
    chat_type text not null default 'private',
    created_at TIMESTAMPTZ not null default NOW(),

    constraint unique_user_chat unique (user_id, chat_id)
)