create table if not exists game_daily (
    id bigint generated by default as identity primary key not null,
    game_id UUID not null,
    created_at TIMESTAMPTZ not null default NOW(),
    ended_at TIMESTAMPTZ default null,

    foreign key (game_id) references game (id)
)