create table if not exists user_source (
    id bigint generated by default as identity primary key not null,
    user_id_int UUID not null,
    user_id_ext text not null,
    "source" text not null,
    created_at TIMESTAMPTZ not null default NOW(),
    
    constraint unique_user_source unique (user_id_ext, "source")
)